apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: pyspark-notebook
  labels:
    app: my-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-notebook
  template:
    metadata:
      labels:
        app: my-notebook
    spec:
      serviceAccountName: spark
      containers:
      - name: my-notebook
        image: hacmao/jupyter-pyspark:3.0.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: pyspark-driver
spec:
  selector:
    app: my-notebook
  ports:
    - protocol: TCP
      port: 29413
  clusterIP: None